// Collects the element boxes captureUi.mjs saved next to each v3 screenshot into src/v3/rects.ts,
// so scenes point at the real UI:   node tools/rectsToTs.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const here = resolve(import.meta.dirname, "..");
const dir = join(here, "public", "shots", "v3");
const out = {};
for (const file of readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .sort()) {
  out[file.replace(/\.json$/, "")] = JSON.parse(readFileSync(join(dir, file), "utf8"));
}
writeFileSync(
  join(here, "src", "v3", "rects.ts"),
  `// Generated by tools/rectsToTs.mjs from the v3 footage: [x, y, width, height] in the\n// screenshots' 2000x1250 CSS-px space. Don't edit by hand; re-run the tool after a re-shoot.\nexport type Rect = readonly [number, number, number, number];\nexport const RECTS: Record<string, Record<string, Rect>> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`wrote ${Object.keys(out).length} shots' rects`);
